unstable_features = true
version = "Two"
max_width = 120
chain_width = 120
fn_single_line = true
where_single_line = true
struct_lit_single_line = true
use_field_init_shorthand = true
trailing_comma = "Vertical"
match_block_trailing_comma = false
format_strings = true
